const config = {
  author: "Saurabh Thakur",
  image_fulls_loc: "/images/fulls",
  image_thumbs_loc: "/images/thumbs",
  google_tag: "G-VNMJYBCT8F",

  title: "Imprints by Saurabh Thakur",
  subtitle: "A display of pictures that I captured",
  header: { title: "Imprints", subtitle: "by Saurabh Thakur" },
  footer: {
    name: "Hey there, my name is Saurabh",
    bio: "I like to click pictures of moments or things that I always want to keep with me forever and this is a place where I would like to share them with the world. There is a ton of beauty around us and this is my way to share it with the world.",
  },
  social: {
    github: "https://github.com/thakursaurabh1998",
  },

  collections: [
    {
      title: "Spiti Valley",
      slug: "/spiti-valley",
      description: "Doremi faso latido Doremi faso latidoDoremi faso latidoDoremi faso latidoDoremi faso latidoDoremi faso latidoDoremi faso latidoDoremi faso latidoDoremi faso latido",
      cover: "IMG_1171.HEIC.jpeg",
      pictures: [
        "/spiti-valley/IMG_0906.heic.jpeg",
        "/spiti-valley/IMG_1045.heic.jpeg",
        "/spiti-valley/IMG_1128.heic.jpeg",
        "/spiti-valley/IMG_1233.HEIC.jpeg",
        "/spiti-valley/IMG_1370.heic.jpeg",
        "/spiti-valley/IMG_0929.heic.jpeg",
        "/spiti-valley/IMG_1064.heic.jpeg",
        "/spiti-valley/IMG_1137.heic.jpeg",
        // "/spiti-valley/IMG_1277.heic.jpeg",
        // "/spiti-valley/IMG_1372.heic.jpeg",
        // "/spiti-valley/IMG_0932.heic.jpeg",
        // "/spiti-valley/IMG_1073.heic.jpeg",
        // "/spiti-valley/IMG_1158.heic.jpeg",
        // "/spiti-valley/IMG_1280.heic.jpeg",
        // "/spiti-valley/IMG_1374.heic.jpeg",
        // "/spiti-valley/IMG_0951.heic.jpeg",
        // "/spiti-valley/IMG_1090.heic.jpeg",
        // "/spiti-valley/IMG_1171.HEIC.jpeg",
        // "/spiti-valley/IMG_1292.heic.jpeg",
        // "/spiti-valley/IMG_1831.HEIC.jpeg",
        // "/spiti-valley/IMG_1039.heic.jpeg",
        // "/spiti-valley/IMG_1106.heic.jpeg",
        // "/spiti-valley/IMG_1229.heic.jpeg",
        // "/spiti-valley/IMG_1354.heic.jpeg",
      ],
    },
    {
      title: "Spiti Valley",
      slug: "/spiti-valley",
      description: "Doremi faso latido",
      cover: "IMG_1171.HEIC.jpeg",
      pictures: [],
    },
    {
      title: "Spiti Valley",
      slug: "/spiti-valley",
      description: "Doremi faso latido",
      cover: "IMG_1831.HEIC.jpeg",
      pictures: [],
    },
    {
      title: "Spiti Valley",
      slug: "/spiti-valley",
      description: "Doremi faso latido",
      cover: "IMG_1171.HEIC.jpeg",
      pictures: [],
    },
    {
      title: "Spiti Valley",
      slug: "/spiti-valley",
      description: "Doremi faso latido",
      cover: "IMG_1171.HEIC.jpeg",
      pictures: [],
    },
  ],
};

export default config;
